let Lookback = 24h;
InsightsMetrics
| where TimeGenerated > ago(Lookback)
| where Namespace == 'LogicalDisk' and Name == 'TransfersPerSecond'
| extend Mount = tostring(todynamic(Tags)['vm.azm.ms/mountId'])
| where isnotempty(Mount)
| where Mount !startswith '/snap/' and Mount !startswith '/sys/'
| summarize MountIOPS = avg(Val) by bin(TimeGenerated, 5m), Computer, Mount
| summarize TotalIOPS = sum(MountIOPS) by TimeGenerated, Computer
| project TimeGenerated, Series = Computer, TotalIOPS
| order by TimeGenerated asc
